(* generated by dune *)

(** @canonical Fstarcompiler.FStarC_Array *)
module FStarC_Array = Fstarcompiler__FStarC_Array

(** @canonical Fstarcompiler.FStarC_BaseTypes *)
module FStarC_BaseTypes = Fstarcompiler__FStarC_BaseTypes

(** @canonical Fstarcompiler.FStarC_BigInt *)
module FStarC_BigInt = Fstarcompiler__FStarC_BigInt

(** @canonical Fstarcompiler.FStarC_Bytes *)
module FStarC_Bytes = Fstarcompiler__FStarC_Bytes

(** @canonical Fstarcompiler.FStarC_CList *)
module FStarC_CList = Fstarcompiler__FStarC_CList

(** @canonical Fstarcompiler.FStarC_CheckedFiles *)
module FStarC_CheckedFiles = Fstarcompiler__FStarC_CheckedFiles

(** @canonical Fstarcompiler.FStarC_Class_Binders *)
module FStarC_Class_Binders = Fstarcompiler__FStarC_Class_Binders

(** @canonical Fstarcompiler.FStarC_Class_Deq *)
module FStarC_Class_Deq = Fstarcompiler__FStarC_Class_Deq

(** @canonical Fstarcompiler.FStarC_Class_HasRange *)
module FStarC_Class_HasRange = Fstarcompiler__FStarC_Class_HasRange

(** @canonical Fstarcompiler.FStarC_Class_Hashable *)
module FStarC_Class_Hashable = Fstarcompiler__FStarC_Class_Hashable

(** @canonical Fstarcompiler.FStarC_Class_Listlike *)
module FStarC_Class_Listlike = Fstarcompiler__FStarC_Class_Listlike

(** @canonical Fstarcompiler.FStarC_Class_Monad *)
module FStarC_Class_Monad = Fstarcompiler__FStarC_Class_Monad

(** @canonical Fstarcompiler.FStarC_Class_Monoid *)
module FStarC_Class_Monoid = Fstarcompiler__FStarC_Class_Monoid

(** @canonical Fstarcompiler.FStarC_Class_Ord *)
module FStarC_Class_Ord = Fstarcompiler__FStarC_Class_Ord

(** @canonical Fstarcompiler.FStarC_Class_PP *)
module FStarC_Class_PP = Fstarcompiler__FStarC_Class_PP

(** @canonical Fstarcompiler.FStarC_Class_Setlike *)
module FStarC_Class_Setlike = Fstarcompiler__FStarC_Class_Setlike

(** @canonical Fstarcompiler.FStarC_Class_Show *)
module FStarC_Class_Show = Fstarcompiler__FStarC_Class_Show

(** @canonical Fstarcompiler.FStarC_Class_Tagged *)
module FStarC_Class_Tagged = Fstarcompiler__FStarC_Class_Tagged

(** @canonical Fstarcompiler.FStarC_Common *)
module FStarC_Common = Fstarcompiler__FStarC_Common

(** @canonical Fstarcompiler.FStarC_Const *)
module FStarC_Const = Fstarcompiler__FStarC_Const

(** @canonical Fstarcompiler.FStarC_Debug *)
module FStarC_Debug = Fstarcompiler__FStarC_Debug

(** @canonical Fstarcompiler.FStarC_Defensive *)
module FStarC_Defensive = Fstarcompiler__FStarC_Defensive

(** @canonical Fstarcompiler.FStarC_Dependencies *)
module FStarC_Dependencies = Fstarcompiler__FStarC_Dependencies

(** @canonical Fstarcompiler.FStarC_Dyn *)
module FStarC_Dyn = Fstarcompiler__FStarC_Dyn

(** @canonical Fstarcompiler.FStarC_Effect *)
module FStarC_Effect = Fstarcompiler__FStarC_Effect

(** @canonical Fstarcompiler.FStarC_Errors *)
module FStarC_Errors = Fstarcompiler__FStarC_Errors

(** @canonical Fstarcompiler.FStarC_Errors_Codes *)
module FStarC_Errors_Codes = Fstarcompiler__FStarC_Errors_Codes

(** @canonical Fstarcompiler.FStarC_Errors_Msg *)
module FStarC_Errors_Msg = Fstarcompiler__FStarC_Errors_Msg

(** @canonical Fstarcompiler.FStarC_Extraction_Krml *)
module FStarC_Extraction_Krml = Fstarcompiler__FStarC_Extraction_Krml

(** @canonical Fstarcompiler.FStarC_Extraction_ML_Code *)
module FStarC_Extraction_ML_Code = Fstarcompiler__FStarC_Extraction_ML_Code

(** @canonical Fstarcompiler.FStarC_Extraction_ML_Modul *)
module FStarC_Extraction_ML_Modul = Fstarcompiler__FStarC_Extraction_ML_Modul

(** @canonical Fstarcompiler.FStarC_Extraction_ML_PrintFS *)
module FStarC_Extraction_ML_PrintFS = Fstarcompiler__FStarC_Extraction_ML_PrintFS

(** @canonical Fstarcompiler.FStarC_Extraction_ML_PrintML *)
module FStarC_Extraction_ML_PrintML = Fstarcompiler__FStarC_Extraction_ML_PrintML

(** @canonical Fstarcompiler.FStarC_Extraction_ML_RegEmb *)
module FStarC_Extraction_ML_RegEmb = Fstarcompiler__FStarC_Extraction_ML_RegEmb

(** @canonical Fstarcompiler.FStarC_Extraction_ML_RemoveUnusedParameters *)
module FStarC_Extraction_ML_RemoveUnusedParameters = Fstarcompiler__FStarC_Extraction_ML_RemoveUnusedParameters

(** @canonical Fstarcompiler.FStarC_Extraction_ML_Syntax *)
module FStarC_Extraction_ML_Syntax = Fstarcompiler__FStarC_Extraction_ML_Syntax

(** @canonical Fstarcompiler.FStarC_Extraction_ML_Term *)
module FStarC_Extraction_ML_Term = Fstarcompiler__FStarC_Extraction_ML_Term

(** @canonical Fstarcompiler.FStarC_Extraction_ML_UEnv *)
module FStarC_Extraction_ML_UEnv = Fstarcompiler__FStarC_Extraction_ML_UEnv

(** @canonical Fstarcompiler.FStarC_Extraction_ML_Util *)
module FStarC_Extraction_ML_Util = Fstarcompiler__FStarC_Extraction_ML_Util

(** @canonical Fstarcompiler.FStarC_Filepath *)
module FStarC_Filepath = Fstarcompiler__FStarC_Filepath

(** @canonical Fstarcompiler.FStarC_Find *)
module FStarC_Find = Fstarcompiler__FStarC_Find

(** @canonical Fstarcompiler.FStarC_Find_Z3 *)
module FStarC_Find_Z3 = Fstarcompiler__FStarC_Find_Z3

(** @canonical Fstarcompiler.FStarC_FlatSet *)
module FStarC_FlatSet = Fstarcompiler__FStarC_FlatSet

(** @canonical Fstarcompiler.FStarC_GenSym *)
module FStarC_GenSym = Fstarcompiler__FStarC_GenSym

(** @canonical Fstarcompiler.FStarC_Getopt *)
module FStarC_Getopt = Fstarcompiler__FStarC_Getopt

(** @canonical Fstarcompiler.FStarC_Hash *)
module FStarC_Hash = Fstarcompiler__FStarC_Hash

(** @canonical Fstarcompiler.FStarC_Hints *)
module FStarC_Hints = Fstarcompiler__FStarC_Hints

(** @canonical Fstarcompiler.FStarC_Hooks *)
module FStarC_Hooks = Fstarcompiler__FStarC_Hooks

(** @canonical Fstarcompiler.FStarC_Ident *)
module FStarC_Ident = Fstarcompiler__FStarC_Ident

(** @canonical Fstarcompiler.FStarC_Interactive_CompletionTable *)
module FStarC_Interactive_CompletionTable = Fstarcompiler__FStarC_Interactive_CompletionTable

(** @canonical Fstarcompiler.FStarC_Interactive_Ide *)
module FStarC_Interactive_Ide = Fstarcompiler__FStarC_Interactive_Ide

(** @canonical Fstarcompiler.FStarC_Interactive_Ide_Types *)
module FStarC_Interactive_Ide_Types = Fstarcompiler__FStarC_Interactive_Ide_Types

(** @canonical Fstarcompiler.FStarC_Interactive_Incremental *)
module FStarC_Interactive_Incremental = Fstarcompiler__FStarC_Interactive_Incremental

(** @canonical Fstarcompiler.FStarC_Interactive_JsonHelper *)
module FStarC_Interactive_JsonHelper = Fstarcompiler__FStarC_Interactive_JsonHelper

(** @canonical Fstarcompiler.FStarC_Interactive_Legacy *)
module FStarC_Interactive_Legacy = Fstarcompiler__FStarC_Interactive_Legacy

(** @canonical Fstarcompiler.FStarC_Interactive_Lsp *)
module FStarC_Interactive_Lsp = Fstarcompiler__FStarC_Interactive_Lsp

(** @canonical Fstarcompiler.FStarC_Interactive_PushHelper *)
module FStarC_Interactive_PushHelper = Fstarcompiler__FStarC_Interactive_PushHelper

(** @canonical Fstarcompiler.FStarC_Interactive_QueryHelper *)
module FStarC_Interactive_QueryHelper = Fstarcompiler__FStarC_Interactive_QueryHelper

(** @canonical Fstarcompiler.FStarC_Json *)
module FStarC_Json = Fstarcompiler__FStarC_Json

(** @canonical Fstarcompiler.FStarC_List *)
module FStarC_List = Fstarcompiler__FStarC_List

(** @canonical Fstarcompiler.FStarC_MachineInts *)
module FStarC_MachineInts = Fstarcompiler__FStarC_MachineInts

(** @canonical Fstarcompiler.FStarC_Main *)
module FStarC_Main = Fstarcompiler__FStarC_Main

(** @canonical Fstarcompiler.FStarC_Misc *)
module FStarC_Misc = Fstarcompiler__FStarC_Misc

(** @canonical Fstarcompiler.FStarC_NormSteps *)
module FStarC_NormSteps = Fstarcompiler__FStarC_NormSteps

(** @canonical Fstarcompiler.FStarC_OCaml *)
module FStarC_OCaml = Fstarcompiler__FStarC_OCaml

(** @canonical Fstarcompiler.FStarC_Option *)
module FStarC_Option = Fstarcompiler__FStarC_Option

(** @canonical Fstarcompiler.FStarC_Options *)
module FStarC_Options = Fstarcompiler__FStarC_Options

(** @canonical Fstarcompiler.FStarC_Options_Ext *)
module FStarC_Options_Ext = Fstarcompiler__FStarC_Options_Ext

(** @canonical Fstarcompiler.FStarC_Order *)
module FStarC_Order = Fstarcompiler__FStarC_Order

(** @canonical Fstarcompiler.FStarC_PIMap *)
module FStarC_PIMap = Fstarcompiler__FStarC_PIMap

(** @canonical Fstarcompiler.FStarC_PSMap *)
module FStarC_PSMap = Fstarcompiler__FStarC_PSMap

(** @canonical Fstarcompiler.FStarC_Parser_AST *)
module FStarC_Parser_AST = Fstarcompiler__FStarC_Parser_AST

(** @canonical Fstarcompiler.FStarC_Parser_AST_Util *)
module FStarC_Parser_AST_Util = Fstarcompiler__FStarC_Parser_AST_Util

(** @canonical Fstarcompiler.FStarC_Parser_Const *)
module FStarC_Parser_Const = Fstarcompiler__FStarC_Parser_Const

(** @canonical Fstarcompiler.FStarC_Parser_Const_ExtractAs *)
module FStarC_Parser_Const_ExtractAs = Fstarcompiler__FStarC_Parser_Const_ExtractAs

(** @canonical Fstarcompiler.FStarC_Parser_Const_Tuples *)
module FStarC_Parser_Const_Tuples = Fstarcompiler__FStarC_Parser_Const_Tuples

(** @canonical Fstarcompiler.FStarC_Parser_Dep *)
module FStarC_Parser_Dep = Fstarcompiler__FStarC_Parser_Dep

(** @canonical Fstarcompiler.FStarC_Parser_Driver *)
module FStarC_Parser_Driver = Fstarcompiler__FStarC_Parser_Driver

(** @canonical Fstarcompiler.FStarC_Parser_LexFStar *)
module FStarC_Parser_LexFStar = Fstarcompiler__FStarC_Parser_LexFStar

(** @canonical Fstarcompiler.FStarC_Parser_Parse *)
module FStarC_Parser_Parse = Fstarcompiler__FStarC_Parser_Parse

(** @canonical Fstarcompiler.FStarC_Parser_ParseIt *)
module FStarC_Parser_ParseIt = Fstarcompiler__FStarC_Parser_ParseIt

(** @canonical Fstarcompiler.FStarC_Parser_ToDocument *)
module FStarC_Parser_ToDocument = Fstarcompiler__FStarC_Parser_ToDocument

(** @canonical Fstarcompiler.FStarC_Parser_Utf8 *)
module FStarC_Parser_Utf8 = Fstarcompiler__FStarC_Parser_Utf8

(** @canonical Fstarcompiler.FStarC_Parser_Util *)
module FStarC_Parser_Util = Fstarcompiler__FStarC_Parser_Util

(** @canonical Fstarcompiler.FStarC_Path *)
module FStarC_Path = Fstarcompiler__FStarC_Path

(** @canonical Fstarcompiler.FStarC_Platform *)
module FStarC_Platform = Fstarcompiler__FStarC_Platform

(** @canonical Fstarcompiler.FStarC_Platform_Base *)
module FStarC_Platform_Base = Fstarcompiler__FStarC_Platform_Base

(** @canonical Fstarcompiler.FStarC_Plugins *)
module FStarC_Plugins = Fstarcompiler__FStarC_Plugins

(** @canonical Fstarcompiler.FStarC_Plugins_Base *)
module FStarC_Plugins_Base = Fstarcompiler__FStarC_Plugins_Base

(** @canonical Fstarcompiler.FStarC_Pprint *)
module FStarC_Pprint = Fstarcompiler__FStarC_Pprint

(** @canonical Fstarcompiler.FStarC_Prettyprint *)
module FStarC_Prettyprint = Fstarcompiler__FStarC_Prettyprint

(** @canonical Fstarcompiler.FStarC_Profiling *)
module FStarC_Profiling = Fstarcompiler__FStarC_Profiling

(** @canonical Fstarcompiler.FStarC_RBSet *)
module FStarC_RBSet = Fstarcompiler__FStarC_RBSet

(** @canonical Fstarcompiler.FStarC_Range *)
module FStarC_Range = Fstarcompiler__FStarC_Range

(** @canonical Fstarcompiler.FStarC_Range_Ops *)
module FStarC_Range_Ops = Fstarcompiler__FStarC_Range_Ops

(** @canonical Fstarcompiler.FStarC_Range_Type *)
module FStarC_Range_Type = Fstarcompiler__FStarC_Range_Type

(** @canonical Fstarcompiler.FStarC_Real *)
module FStarC_Real = Fstarcompiler__FStarC_Real

(** @canonical Fstarcompiler.FStarC_Reflection_Types *)
module FStarC_Reflection_Types = Fstarcompiler__FStarC_Reflection_Types

(** @canonical Fstarcompiler.FStarC_Reflection_V1_Builtins *)
module FStarC_Reflection_V1_Builtins = Fstarcompiler__FStarC_Reflection_V1_Builtins

(** @canonical Fstarcompiler.FStarC_Reflection_V1_Constants *)
module FStarC_Reflection_V1_Constants = Fstarcompiler__FStarC_Reflection_V1_Constants

(** @canonical Fstarcompiler.FStarC_Reflection_V1_Data *)
module FStarC_Reflection_V1_Data = Fstarcompiler__FStarC_Reflection_V1_Data

(** @canonical Fstarcompiler.FStarC_Reflection_V1_Embeddings *)
module FStarC_Reflection_V1_Embeddings = Fstarcompiler__FStarC_Reflection_V1_Embeddings

(** @canonical Fstarcompiler.FStarC_Reflection_V1_Interpreter *)
module FStarC_Reflection_V1_Interpreter = Fstarcompiler__FStarC_Reflection_V1_Interpreter

(** @canonical Fstarcompiler.FStarC_Reflection_V1_NBEEmbeddings *)
module FStarC_Reflection_V1_NBEEmbeddings = Fstarcompiler__FStarC_Reflection_V1_NBEEmbeddings

(** @canonical Fstarcompiler.FStarC_Reflection_V2_Builtins *)
module FStarC_Reflection_V2_Builtins = Fstarcompiler__FStarC_Reflection_V2_Builtins

(** @canonical Fstarcompiler.FStarC_Reflection_V2_Constants *)
module FStarC_Reflection_V2_Constants = Fstarcompiler__FStarC_Reflection_V2_Constants

(** @canonical Fstarcompiler.FStarC_Reflection_V2_Data *)
module FStarC_Reflection_V2_Data = Fstarcompiler__FStarC_Reflection_V2_Data

(** @canonical Fstarcompiler.FStarC_Reflection_V2_Embeddings *)
module FStarC_Reflection_V2_Embeddings = Fstarcompiler__FStarC_Reflection_V2_Embeddings

(** @canonical Fstarcompiler.FStarC_Reflection_V2_Interpreter *)
module FStarC_Reflection_V2_Interpreter = Fstarcompiler__FStarC_Reflection_V2_Interpreter

(** @canonical Fstarcompiler.FStarC_Reflection_V2_NBEEmbeddings *)
module FStarC_Reflection_V2_NBEEmbeddings = Fstarcompiler__FStarC_Reflection_V2_NBEEmbeddings

(** @canonical Fstarcompiler.FStarC_SMTEncoding_Encode *)
module FStarC_SMTEncoding_Encode = Fstarcompiler__FStarC_SMTEncoding_Encode

(** @canonical Fstarcompiler.FStarC_SMTEncoding_EncodeTerm *)
module FStarC_SMTEncoding_EncodeTerm = Fstarcompiler__FStarC_SMTEncoding_EncodeTerm

(** @canonical Fstarcompiler.FStarC_SMTEncoding_Env *)
module FStarC_SMTEncoding_Env = Fstarcompiler__FStarC_SMTEncoding_Env

(** @canonical Fstarcompiler.FStarC_SMTEncoding_ErrorReporting *)
module FStarC_SMTEncoding_ErrorReporting = Fstarcompiler__FStarC_SMTEncoding_ErrorReporting

(** @canonical Fstarcompiler.FStarC_SMTEncoding_Pruning *)
module FStarC_SMTEncoding_Pruning = Fstarcompiler__FStarC_SMTEncoding_Pruning

(** @canonical Fstarcompiler.FStarC_SMTEncoding_Solver *)
module FStarC_SMTEncoding_Solver = Fstarcompiler__FStarC_SMTEncoding_Solver

(** @canonical Fstarcompiler.FStarC_SMTEncoding_SolverState *)
module FStarC_SMTEncoding_SolverState = Fstarcompiler__FStarC_SMTEncoding_SolverState

(** @canonical Fstarcompiler.FStarC_SMTEncoding_Solver_Cache *)
module FStarC_SMTEncoding_Solver_Cache = Fstarcompiler__FStarC_SMTEncoding_Solver_Cache

(** @canonical Fstarcompiler.FStarC_SMTEncoding_Term *)
module FStarC_SMTEncoding_Term = Fstarcompiler__FStarC_SMTEncoding_Term

(** @canonical Fstarcompiler.FStarC_SMTEncoding_UnsatCore *)
module FStarC_SMTEncoding_UnsatCore = Fstarcompiler__FStarC_SMTEncoding_UnsatCore

(** @canonical Fstarcompiler.FStarC_SMTEncoding_Util *)
module FStarC_SMTEncoding_Util = Fstarcompiler__FStarC_SMTEncoding_Util

(** @canonical Fstarcompiler.FStarC_SMTEncoding_Z3 *)
module FStarC_SMTEncoding_Z3 = Fstarcompiler__FStarC_SMTEncoding_Z3

(** @canonical Fstarcompiler.FStarC_SMap *)
module FStarC_SMap = Fstarcompiler__FStarC_SMap

(** @canonical Fstarcompiler.FStarC_Sealed *)
module FStarC_Sealed = Fstarcompiler__FStarC_Sealed

(** @canonical Fstarcompiler.FStarC_Sedlexing *)
module FStarC_Sedlexing = Fstarcompiler__FStarC_Sedlexing

(** @canonical Fstarcompiler.FStarC_String *)
module FStarC_String = Fstarcompiler__FStarC_String

(** @canonical Fstarcompiler.FStarC_StringBuffer *)
module FStarC_StringBuffer = Fstarcompiler__FStarC_StringBuffer

(** @canonical Fstarcompiler.FStarC_Syntax_Compress *)
module FStarC_Syntax_Compress = Fstarcompiler__FStarC_Syntax_Compress

(** @canonical Fstarcompiler.FStarC_Syntax_DsEnv *)
module FStarC_Syntax_DsEnv = Fstarcompiler__FStarC_Syntax_DsEnv

(** @canonical Fstarcompiler.FStarC_Syntax_Embeddings *)
module FStarC_Syntax_Embeddings = Fstarcompiler__FStarC_Syntax_Embeddings

(** @canonical Fstarcompiler.FStarC_Syntax_Embeddings_AppEmb *)
module FStarC_Syntax_Embeddings_AppEmb = Fstarcompiler__FStarC_Syntax_Embeddings_AppEmb

(** @canonical Fstarcompiler.FStarC_Syntax_Embeddings_Base *)
module FStarC_Syntax_Embeddings_Base = Fstarcompiler__FStarC_Syntax_Embeddings_Base

(** @canonical Fstarcompiler.FStarC_Syntax_Formula *)
module FStarC_Syntax_Formula = Fstarcompiler__FStarC_Syntax_Formula

(** @canonical Fstarcompiler.FStarC_Syntax_Free *)
module FStarC_Syntax_Free = Fstarcompiler__FStarC_Syntax_Free

(** @canonical Fstarcompiler.FStarC_Syntax_Hash *)
module FStarC_Syntax_Hash = Fstarcompiler__FStarC_Syntax_Hash

(** @canonical Fstarcompiler.FStarC_Syntax_InstFV *)
module FStarC_Syntax_InstFV = Fstarcompiler__FStarC_Syntax_InstFV

(** @canonical Fstarcompiler.FStarC_Syntax_MutRecTy *)
module FStarC_Syntax_MutRecTy = Fstarcompiler__FStarC_Syntax_MutRecTy

(** @canonical Fstarcompiler.FStarC_Syntax_Print *)
module FStarC_Syntax_Print = Fstarcompiler__FStarC_Syntax_Print

(** @canonical Fstarcompiler.FStarC_Syntax_Print_Pretty *)
module FStarC_Syntax_Print_Pretty = Fstarcompiler__FStarC_Syntax_Print_Pretty

(** @canonical Fstarcompiler.FStarC_Syntax_Print_Ugly *)
module FStarC_Syntax_Print_Ugly = Fstarcompiler__FStarC_Syntax_Print_Ugly

(** @canonical Fstarcompiler.FStarC_Syntax_Resugar *)
module FStarC_Syntax_Resugar = Fstarcompiler__FStarC_Syntax_Resugar

(** @canonical Fstarcompiler.FStarC_Syntax_Subst *)
module FStarC_Syntax_Subst = Fstarcompiler__FStarC_Syntax_Subst

(** @canonical Fstarcompiler.FStarC_Syntax_Syntax *)
module FStarC_Syntax_Syntax = Fstarcompiler__FStarC_Syntax_Syntax

(** @canonical Fstarcompiler.FStarC_Syntax_TermHashTable *)
module FStarC_Syntax_TermHashTable = Fstarcompiler__FStarC_Syntax_TermHashTable

(** @canonical Fstarcompiler.FStarC_Syntax_Unionfind *)
module FStarC_Syntax_Unionfind = Fstarcompiler__FStarC_Syntax_Unionfind

(** @canonical Fstarcompiler.FStarC_Syntax_Util *)
module FStarC_Syntax_Util = Fstarcompiler__FStarC_Syntax_Util

(** @canonical Fstarcompiler.FStarC_Syntax_Visit *)
module FStarC_Syntax_Visit = Fstarcompiler__FStarC_Syntax_Visit

(** @canonical Fstarcompiler.FStarC_Syntax_VisitM *)
module FStarC_Syntax_VisitM = Fstarcompiler__FStarC_Syntax_VisitM

(** @canonical Fstarcompiler.FStarC_Tactics_Common *)
module FStarC_Tactics_Common = Fstarcompiler__FStarC_Tactics_Common

(** @canonical Fstarcompiler.FStarC_Tactics_CtrlRewrite *)
module FStarC_Tactics_CtrlRewrite = Fstarcompiler__FStarC_Tactics_CtrlRewrite

(** @canonical Fstarcompiler.FStarC_Tactics_Embedding *)
module FStarC_Tactics_Embedding = Fstarcompiler__FStarC_Tactics_Embedding

(** @canonical Fstarcompiler.FStarC_Tactics_Hooks *)
module FStarC_Tactics_Hooks = Fstarcompiler__FStarC_Tactics_Hooks

(** @canonical Fstarcompiler.FStarC_Tactics_InterpFuns *)
module FStarC_Tactics_InterpFuns = Fstarcompiler__FStarC_Tactics_InterpFuns

(** @canonical Fstarcompiler.FStarC_Tactics_Interpreter *)
module FStarC_Tactics_Interpreter = Fstarcompiler__FStarC_Tactics_Interpreter

(** @canonical Fstarcompiler.FStarC_Tactics_Monad *)
module FStarC_Tactics_Monad = Fstarcompiler__FStarC_Tactics_Monad

(** @canonical Fstarcompiler.FStarC_Tactics_Native *)
module FStarC_Tactics_Native = Fstarcompiler__FStarC_Tactics_Native

(** @canonical Fstarcompiler.FStarC_Tactics_Printing *)
module FStarC_Tactics_Printing = Fstarcompiler__FStarC_Tactics_Printing

(** @canonical Fstarcompiler.FStarC_Tactics_Result *)
module FStarC_Tactics_Result = Fstarcompiler__FStarC_Tactics_Result

(** @canonical Fstarcompiler.FStarC_Tactics_Types *)
module FStarC_Tactics_Types = Fstarcompiler__FStarC_Tactics_Types

(** @canonical Fstarcompiler.FStarC_Tactics_Types_Reflection *)
module FStarC_Tactics_Types_Reflection = Fstarcompiler__FStarC_Tactics_Types_Reflection

(** @canonical Fstarcompiler.FStarC_Tactics_V1_Basic *)
module FStarC_Tactics_V1_Basic = Fstarcompiler__FStarC_Tactics_V1_Basic

(** @canonical Fstarcompiler.FStarC_Tactics_V1_Primops *)
module FStarC_Tactics_V1_Primops = Fstarcompiler__FStarC_Tactics_V1_Primops

(** @canonical Fstarcompiler.FStarC_Tactics_V2_Basic *)
module FStarC_Tactics_V2_Basic = Fstarcompiler__FStarC_Tactics_V2_Basic

(** @canonical Fstarcompiler.FStarC_Tactics_V2_Primops *)
module FStarC_Tactics_V2_Primops = Fstarcompiler__FStarC_Tactics_V2_Primops

(** @canonical Fstarcompiler.FStarC_Thunk *)
module FStarC_Thunk = Fstarcompiler__FStarC_Thunk

(** @canonical Fstarcompiler.FStarC_Timing *)
module FStarC_Timing = Fstarcompiler__FStarC_Timing

(** @canonical Fstarcompiler.FStarC_ToSyntax_Interleave *)
module FStarC_ToSyntax_Interleave = Fstarcompiler__FStarC_ToSyntax_Interleave

(** @canonical Fstarcompiler.FStarC_ToSyntax_ToSyntax *)
module FStarC_ToSyntax_ToSyntax = Fstarcompiler__FStarC_ToSyntax_ToSyntax

(** @canonical Fstarcompiler.FStarC_TypeChecker_Cfg *)
module FStarC_TypeChecker_Cfg = Fstarcompiler__FStarC_TypeChecker_Cfg

(** @canonical Fstarcompiler.FStarC_TypeChecker_Common *)
module FStarC_TypeChecker_Common = Fstarcompiler__FStarC_TypeChecker_Common

(** @canonical Fstarcompiler.FStarC_TypeChecker_Core *)
module FStarC_TypeChecker_Core = Fstarcompiler__FStarC_TypeChecker_Core

(** @canonical Fstarcompiler.FStarC_TypeChecker_DMFF *)
module FStarC_TypeChecker_DMFF = Fstarcompiler__FStarC_TypeChecker_DMFF

(** @canonical Fstarcompiler.FStarC_TypeChecker_DeferredImplicits *)
module FStarC_TypeChecker_DeferredImplicits = Fstarcompiler__FStarC_TypeChecker_DeferredImplicits

(** @canonical Fstarcompiler.FStarC_TypeChecker_Env *)
module FStarC_TypeChecker_Env = Fstarcompiler__FStarC_TypeChecker_Env

(** @canonical Fstarcompiler.FStarC_TypeChecker_Err *)
module FStarC_TypeChecker_Err = Fstarcompiler__FStarC_TypeChecker_Err

(** @canonical Fstarcompiler.FStarC_TypeChecker_Generalize *)
module FStarC_TypeChecker_Generalize = Fstarcompiler__FStarC_TypeChecker_Generalize

(** @canonical Fstarcompiler.FStarC_TypeChecker_NBE *)
module FStarC_TypeChecker_NBE = Fstarcompiler__FStarC_TypeChecker_NBE

(** @canonical Fstarcompiler.FStarC_TypeChecker_NBETerm *)
module FStarC_TypeChecker_NBETerm = Fstarcompiler__FStarC_TypeChecker_NBETerm

(** @canonical Fstarcompiler.FStarC_TypeChecker_Normalize *)
module FStarC_TypeChecker_Normalize = Fstarcompiler__FStarC_TypeChecker_Normalize

(** @canonical Fstarcompiler.FStarC_TypeChecker_Normalize_Unfolding *)
module FStarC_TypeChecker_Normalize_Unfolding = Fstarcompiler__FStarC_TypeChecker_Normalize_Unfolding

(** @canonical Fstarcompiler.FStarC_TypeChecker_PatternUtils *)
module FStarC_TypeChecker_PatternUtils = Fstarcompiler__FStarC_TypeChecker_PatternUtils

(** @canonical Fstarcompiler.FStarC_TypeChecker_Positivity *)
module FStarC_TypeChecker_Positivity = Fstarcompiler__FStarC_TypeChecker_Positivity

(** @canonical Fstarcompiler.FStarC_TypeChecker_Primops *)
module FStarC_TypeChecker_Primops = Fstarcompiler__FStarC_TypeChecker_Primops

(** @canonical Fstarcompiler.FStarC_TypeChecker_Primops_Array *)
module FStarC_TypeChecker_Primops_Array = Fstarcompiler__FStarC_TypeChecker_Primops_Array

(** @canonical Fstarcompiler.FStarC_TypeChecker_Primops_Base *)
module FStarC_TypeChecker_Primops_Base = Fstarcompiler__FStarC_TypeChecker_Primops_Base

(** @canonical Fstarcompiler.FStarC_TypeChecker_Primops_Docs *)
module FStarC_TypeChecker_Primops_Docs = Fstarcompiler__FStarC_TypeChecker_Primops_Docs

(** @canonical Fstarcompiler.FStarC_TypeChecker_Primops_Eq *)
module FStarC_TypeChecker_Primops_Eq = Fstarcompiler__FStarC_TypeChecker_Primops_Eq

(** @canonical Fstarcompiler.FStarC_TypeChecker_Primops_Erased *)
module FStarC_TypeChecker_Primops_Erased = Fstarcompiler__FStarC_TypeChecker_Primops_Erased

(** @canonical Fstarcompiler.FStarC_TypeChecker_Primops_Errors_Msg *)
module FStarC_TypeChecker_Primops_Errors_Msg = Fstarcompiler__FStarC_TypeChecker_Primops_Errors_Msg

(** @canonical Fstarcompiler.FStarC_TypeChecker_Primops_Issue *)
module FStarC_TypeChecker_Primops_Issue = Fstarcompiler__FStarC_TypeChecker_Primops_Issue

(** @canonical Fstarcompiler.FStarC_TypeChecker_Primops_MachineInts *)
module FStarC_TypeChecker_Primops_MachineInts = Fstarcompiler__FStarC_TypeChecker_Primops_MachineInts

(** @canonical Fstarcompiler.FStarC_TypeChecker_Primops_Range *)
module FStarC_TypeChecker_Primops_Range = Fstarcompiler__FStarC_TypeChecker_Primops_Range

(** @canonical Fstarcompiler.FStarC_TypeChecker_Primops_Real *)
module FStarC_TypeChecker_Primops_Real = Fstarcompiler__FStarC_TypeChecker_Primops_Real

(** @canonical Fstarcompiler.FStarC_TypeChecker_Primops_Sealed *)
module FStarC_TypeChecker_Primops_Sealed = Fstarcompiler__FStarC_TypeChecker_Primops_Sealed

(** @canonical Fstarcompiler.FStarC_TypeChecker_Quals *)
module FStarC_TypeChecker_Quals = Fstarcompiler__FStarC_TypeChecker_Quals

(** @canonical Fstarcompiler.FStarC_TypeChecker_Rel *)
module FStarC_TypeChecker_Rel = Fstarcompiler__FStarC_TypeChecker_Rel

(** @canonical Fstarcompiler.FStarC_TypeChecker_Tc *)
module FStarC_TypeChecker_Tc = Fstarcompiler__FStarC_TypeChecker_Tc

(** @canonical Fstarcompiler.FStarC_TypeChecker_TcEffect *)
module FStarC_TypeChecker_TcEffect = Fstarcompiler__FStarC_TypeChecker_TcEffect

(** @canonical Fstarcompiler.FStarC_TypeChecker_TcInductive *)
module FStarC_TypeChecker_TcInductive = Fstarcompiler__FStarC_TypeChecker_TcInductive

(** @canonical Fstarcompiler.FStarC_TypeChecker_TcTerm *)
module FStarC_TypeChecker_TcTerm = Fstarcompiler__FStarC_TypeChecker_TcTerm

(** @canonical Fstarcompiler.FStarC_TypeChecker_TermEqAndSimplify *)
module FStarC_TypeChecker_TermEqAndSimplify = Fstarcompiler__FStarC_TypeChecker_TermEqAndSimplify

(** @canonical Fstarcompiler.FStarC_TypeChecker_Util *)
module FStarC_TypeChecker_Util = Fstarcompiler__FStarC_TypeChecker_Util

(** @canonical Fstarcompiler.FStarC_Unionfind *)
module FStarC_Unionfind = Fstarcompiler__FStarC_Unionfind

(** @canonical Fstarcompiler.FStarC_Universal *)
module FStarC_Universal = Fstarcompiler__FStarC_Universal

(** @canonical Fstarcompiler.FStarC_Util *)
module FStarC_Util = Fstarcompiler__FStarC_Util

(** @canonical Fstarcompiler.FStarC_VConfig *)
module FStarC_VConfig = Fstarcompiler__FStarC_VConfig

(** @canonical Fstarcompiler.FStarC_Version *)
module FStarC_Version = Fstarcompiler__FStarC_Version

(** @canonical Fstarcompiler.FStarC_Writer *)
module FStarC_Writer = Fstarcompiler__FStarC_Writer

(** @canonical Fstarcompiler.FStar_All *)
module FStar_All = Fstarcompiler__FStar_All

(** @canonical Fstarcompiler.FStar_Bytes *)
module FStar_Bytes = Fstarcompiler__FStar_Bytes

(** @canonical Fstarcompiler.FStar_Char *)
module FStar_Char = Fstarcompiler__FStar_Char

(** @canonical Fstarcompiler.FStar_CommonST *)
module FStar_CommonST = Fstarcompiler__FStar_CommonST

(** @canonical Fstarcompiler.FStar_Exn *)
module FStar_Exn = Fstarcompiler__FStar_Exn

(** @canonical Fstarcompiler.FStar_Float *)
module FStar_Float = Fstarcompiler__FStar_Float

(** @canonical Fstarcompiler.FStar_Heap *)
module FStar_Heap = Fstarcompiler__FStar_Heap

(** @canonical Fstarcompiler.FStar_IO *)
module FStar_IO = Fstarcompiler__FStar_IO

(** @canonical Fstarcompiler.FStar_ImmutableArray *)
module FStar_ImmutableArray = Fstarcompiler__FStar_ImmutableArray

(** @canonical Fstarcompiler.FStar_ImmutableArray_Base *)
module FStar_ImmutableArray_Base = Fstarcompiler__FStar_ImmutableArray_Base

(** @canonical Fstarcompiler.FStar_Int16 *)
module FStar_Int16 = Fstarcompiler__FStar_Int16

(** @canonical Fstarcompiler.FStar_Int32 *)
module FStar_Int32 = Fstarcompiler__FStar_Int32

(** @canonical Fstarcompiler.FStar_Int64 *)
module FStar_Int64 = Fstarcompiler__FStar_Int64

(** @canonical Fstarcompiler.FStar_Int8 *)
module FStar_Int8 = Fstarcompiler__FStar_Int8

(** @canonical Fstarcompiler.FStar_List *)
module FStar_List = Fstarcompiler__FStar_List

(** @canonical Fstarcompiler.FStar_List_Tot_Base *)
module FStar_List_Tot_Base = Fstarcompiler__FStar_List_Tot_Base

(** @canonical Fstarcompiler.FStar_Monotonic_Heap *)
module FStar_Monotonic_Heap = Fstarcompiler__FStar_Monotonic_Heap

(** @canonical Fstarcompiler.FStar_Option *)
module FStar_Option = Fstarcompiler__FStar_Option

(** @canonical Fstarcompiler.FStar_Pervasives *)
module FStar_Pervasives = Fstarcompiler__FStar_Pervasives

(** @canonical Fstarcompiler.FStar_Pervasives_Native *)
module FStar_Pervasives_Native = Fstarcompiler__FStar_Pervasives_Native

(** @canonical Fstarcompiler.FStar_Pprint *)
module FStar_Pprint = Fstarcompiler__FStar_Pprint

(** @canonical Fstarcompiler.FStar_ST *)
module FStar_ST = Fstarcompiler__FStar_ST

(** @canonical Fstarcompiler.FStar_Seq_Base *)
module FStar_Seq_Base = Fstarcompiler__FStar_Seq_Base

(** @canonical Fstarcompiler.FStar_Seq_Properties *)
module FStar_Seq_Properties = Fstarcompiler__FStar_Seq_Properties

(** @canonical Fstarcompiler.FStar_String *)
module FStar_String = Fstarcompiler__FStar_String

(** @canonical Fstarcompiler.FStar_UInt16 *)
module FStar_UInt16 = Fstarcompiler__FStar_UInt16

(** @canonical Fstarcompiler.FStar_UInt32 *)
module FStar_UInt32 = Fstarcompiler__FStar_UInt32

(** @canonical Fstarcompiler.FStar_UInt64 *)
module FStar_UInt64 = Fstarcompiler__FStar_UInt64

(** @canonical Fstarcompiler.FStar_UInt8 *)
module FStar_UInt8 = Fstarcompiler__FStar_UInt8

(** @canonical Fstarcompiler.Prims *)
module Prims = Fstarcompiler__Prims
